### PR TITLE
Fix crash with lint

### PR DESCRIPTION
**Pull request by patedit**

### CODE REVIEW

**Comment by edenman** [comment]
Was it intentional that this change makes the `BLUETOOTH` permission required?

**Comment by patedit** [comment]
Hi @edenman! I gave it some thought and since BLUETOOTH permission is considered as [normal](https://developer.android.com/reference/android/Manifest.permission.html#BLUETOOTH), the system will grant access automatically and won't prompt the user. Also, this would fix this crash indirectly https://github.com/mixpanel/mixpanel-android/issues/424 - Please, let me know what you think and if you have a case where you don't want that permission to be merged on your manifest file.

**Comment by edenman** [comment]
Hm.  I upgraded to mixpanel-android 4.9.7 and I get this warning in the Play store when I go to publish it:
screen shot 2017-03-02 at 2 28 49 pm

Maybe the warning doesn't take into account protection levels?

**Comment by patedit** [comment]
Thanks for the info! That warning is pretty annoying and I'm sure that many other developers will have the same concern as you. You can read the second paragraph of [this link](https://developer.android.com/guide/topics/permissions/normal-permissions.html) and see that the system grants access automatically to normal permissions. 

In your case I think users won't have to accept the BLUETOOTH permission. If it's a real concern for you right now I have no problem in removing the permission and create a release. Let me know what you prefer.

**Comment by edenman** [comment]
I think the warning is actually correct. https://support.google.com/googleplay/answer/6014972 seems to indicate that adding Bluetooth permission will keep auto-update from applying.

**Comment by edenman** [comment]
(confirmed this with somebody at Google.  i'll just remove the permission in my manifest for now)

**Comment by patedit** [comment]
Ah, interesting. I did not consider that. The best thing will be to remove it from the SDK as well. Thanks a lot for your useful feedback :)

**Comment by edenman** [comment]
👍

**Comment by smithaaron** [comment]
I also inexplicably received this warning when uploading a new build to the store. It was puzzling at first since I hadn't made any manifest or dependency changes. Eventually I realised it was due to mixpanel, as I had my dependency using a '+' as per your docs
`compile "com.mixpanel.android:mixpanel-android:4.+`

I now have 4.9.6 hardcoded as I don't need nor want to add the Bluetooth permission. Please apply a proper fix instead of forcing this on people.

**Comment by ming13** [comment]
Patiently awaiting for a next release for now...

**Comment by patedit** [comment]
@edenman @ming13 @smithaaron I removed this permission in the latest release 4.9.8. sorry for the inconvenience guys :)

**Pull request merged**
