### PR TITLE
Fix worker crash when fallabck endpoint disabled

### PR DESCRIPTION
**Pull request by baolongnt**

### CODE REVIEW

**Comment by joeatwork** [comment]
Thanks! This is already cooking for the next release, and will be included in 4.5.4. In the mean time the workaround is to disable debug output in your app by removing the com.mixpanel.android.MPConfig.EnableDebugLogging directive from your AndroidManifest.xml

**Comment by joeatwork** [comment]
(Also, thank you for sending this fix! We really appreciate the help!)

**Comment by baolongnt** [comment]
No pb. When do you think 4.5.4 will be out? Right now, that debug feature is not usable.

**Comment by joeatwork** [comment]
We're working on it now (you can actually watch our progress on branch v4.5.4dev ( https://github.com/mixpanel/mixpanel-android/tree/v4.5.4dev )!

If debug output is helpful to you, can also work around the issue by turning on HTTP fallback if you need the debug output during development- while you probably shouldn't ship with fallback on unless your app is targeting particular markets or unique circumstances, the same is true for shipping with debug output.

**Comment by baolongnt** [comment]
Thanks for the workaround.

**Pull request closed without merging**
