### PR TITLE
Allow changing event endpoint at runtime through MPConfig

### PR DESCRIPTION
**Pull request by patedit**
Change mp default event tracking endpoint (https://api.mixpanel.com/track?ip=1) at runtime by running the following:
```
MPConfig.getInstance(this).setEventsEndpoint("https://myapp.company.com/trackendpoint/");
```

(*) Remember that if you just need to override our tracking endpoint always, you are safe by keeping using the following meta-tag in your `AndroidManifest.xml`

```
<meta-data android:name="com.mixpanel.android.MPConfig.EventsEndpoint"
            android:value="https://myapp.company.com/trackendpoint/" />
```

### CODE REVIEW

**Comment by drauly** [comment]
Hello @patedit,

This seems to be ok for me.
Just 2 questions :
- Is it possible to apply the same change to peopleEndpoint ?
- Is it possible to have convinience for default url ?

eg : setEventEndpoint() => no parameter => https://api.mixpanel.com/track?ip=1

This could avoid missing the ?ip=1

What do you think ?

Thank you for the changes.

**Comment by drauly** [comment]
Hello @patedit,

Do you have any update ?

**Comment by patedit** [comment]
@drauly what do you think about my last commit?

thanks!

**Comment by drauly** [comment]
Hey,

This looks good to me.
Do you have any idea of a merge/release date ?

Thanks you again

**Comment by patedit** [comment]
@drauly just made a [new release](https://github.com/mixpanel/mixpanel-android/releases/tag/v5.3.0) :)

**Comment by drauly** [comment]
Great!
Thanks you @patedit :)

**Pull request merged**
