### PR TITLE
Add spanish translation for surveys

### PR DESCRIPTION
**Pull request by cokeperez**

### CODE REVIEW

**Comment by patedit** [comment]
Thanks a lot @cokeperez !

There's something that could be misinterpreted. When prompting the question "Te importaria contestar a alguna pregunta?" one of the choices is "Claro". In English "Sure" could be valid but in Spanish "Claro" means exactly the opposite for this example. I would change the question and/or "Claro". What do you think? As a spanish speaker I know this is tricky :)

**Comment by papajulio** [comment]
@patedit I would change the question it's quite tricky. @cokeperez what do you think about 
'¿Quieres contestar alguna pregunta?' or something similar so the answer fits better?

**Comment by cokeperez** [comment]
@patedit @papajulio thank you for your feedback.

The original question in english is '_Mind taking a quick survey?_' so maybe we can put '_¿Podrías contestar una breve encuesta?_'

What do you think?

**Comment by patedit** [comment]
I like it! As soon as you change it, I'll merge your PR. Thanks @cokeperez @papajulio

**Comment by cokeperez** [comment]
Done :)

Thx @patedit!

**Comment by patedit** [comment]
Thanks guys!

**Pull request merged**
