### PR TITLE
Add Proguard rules to library using consumerProguardFiles

### LINKED ISSUE #351: Include Proguard configuration in library
Can be done using `consumerProguardFile`. If you want I'd be more than happy to provide a PR for that.

### PR DESCRIPTION
**Pull request by vanniktech**
Will fix #351

### CODE REVIEW

**Comment by vanniktech** [comment]
Friendly ping @patedit

**Comment by patedit** [comment]
Thanks @vanniktech - Can we rename `proguard-rules.txt` to `proguard.txt` as per Android' suggestion? http://tools.android.com/tech-docs/new-build-system/aar-format

**Comment by vanniktech** [comment]
Done

**Comment by patedit** [comment]
Thanks a lot!

**Pull request merged**
