### PR TITLE
fix for NPE in case if File.listFiles returns null

### PR DESCRIPTION
**Pull request by andrey-starodubtsev**
fix for NPE found via ACRA, according http://developer.android.com/reference/java/io/File.html#listFiles(), `File.listFiles` can return `null`

### CODE REVIEW

**Comment by patedit** [comment]
Hi @andrey-starodubtsev Even if this PR would solve a crash in that line, it seems the problem may be somewhere else. If `listFiles` returns `null` is only because `mDirectory` is not a directory and that should never happen. Do you have some logs I could take a look? What is the Mixpanel SDK version you are using? Thanks!

**Comment by andrey-starodubtsev** [comment]
Hello, @patedit. I got crashes via ACRA while using this method in our code and added check for null everywhere, including 3-rd party libraries we use in our product, just in case.

**Comment by patedit** [comment]
Any of your crashes were coming from our library?

**Comment by patedit** [comment]
@andrey-starodubtsev Will close this PR but feel free to open an issue if you see a crash coming from our library. Thanks!

**Pull request closed without merging**
