### PR TITLE
Add SessionReplayBroadcastReceiver

### PR DESCRIPTION
**Pull request by jaredmixpanel**
Add a broadcast receiver to receive the `$mp_replay_id` from the Session Replay SDK

### CODE REVIEW

**Review by zihejia — APPROVED** [review]
LGTM

**Comment by carstenhag** [comment]
This change (and 7.5.2 -> 7.5.3) somehow breaks tests for me (when MixpanelAPI is instantiated).

```
Permission com.digitalchargingsolutions.b2c.integ.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION is required by your application to receive broadcasts, please add it to your manifest
java.lang.RuntimeException: Permission com.digitalchargingsolutions.b2c.integ.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION is required by your application to receive broadcasts, please add it to your manifest
	at androidx.core.content.ContextCompat.obtainAndCheckReceiverPermission(ContextCompat.java:970)
	at androidx.core.content.ContextCompat$Api26Impl.registerReceiver(ContextCompat.java:1117)
	at androidx.core.content.ContextCompat.registerReceiver(ContextCompat.java:822)
	at androidx.core.content.ContextCompat.registerReceiver(ContextCompat.java:769)
	at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:199)
	at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:123)
	at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:463)
	at com.bmw.chargenow.utils.analytics.AnalyticsTracker.<init>(AnalyticsTracker.kt:42)
```

MixpanelAPI.java:199 points to 

```
       ContextCompat.registerReceiver(
                mContext.getApplicationContext(),
                sessionReplayReceiver,
                SessionReplayBroadcastReceiver.INTENT_FILTER,
                ContextCompat.RECEIVER_NOT_EXPORTED
        );
```

I have tried adding `<uses-permission android:name="${applicationId}.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" />` to the manifest, but that didn't help. Could also not solve it by quick googling.

**Comment by jaredmixpanel** [comment]
@carstenhag Are your tests running with `targetSdk` <= 32? If so, can you bump that up to >=33? 

I found this other Github issue which seems relevant here: https://github.com/robolectric/robolectric/issues/9124

**Comment by carstenhag** [comment]
Yep Robolectric was the issue, thank you! We were specifying `@Config(sdk = [Build.VERSION_CODES.P])`, afaik due to an old bug, but it seems resolved, so now we are using the default (latest sdk).

**Pull request merged**
