### PR TITLE
Updating Gradle (v1.3.0-beta4), adding/committing the Gradle wrapper …

### PR DESCRIPTION
**Pull request by justincpollard**
…to git, and updating the Android library plugin. Also fixing/ignoring various lint errors.

### CODE REVIEW

**Comment by arittr** [comment]
@yinfeiru can you take a look at this ?

**Comment by arittr** [comment]
@yinfeiru any way we can update gradlew here?

**Comment by yinfeiru** [comment]
@justincpollard thanks for the pr! since the lib has been changed a lot, I'll make a new pr and have your updates there.

**Comment by justincpollard** [comment]
@yinfeiru cool, thanks!

**Pull request closed without merging**
