### PR TITLE
Adding flags to disable notifications and surveys to avoid unneeded d…

### PR DESCRIPTION
**Pull request by yinfeiru**
…ecide requests

### CODE REVIEW

**Comment by ryanseams** [comment]
these config options will disable a/b tests as well right? why not have one configuration option to just turn off decide rather than multiple options where the end user will not know turning off one also turns off the other features?

**Comment by yinfeiru** [comment]
@ryanseams nice catch and I agree with the idea of turning decide check of.

**Comment by patedit** [comment]
This is not a good solution in general. Besides what @ryanseams said, current implementation will disable everything (tweaks, notifications, surveys...) only by having notifications OR surveys off.

**Comment by yinfeiru** [comment]
duplicate.. closing

**Pull request closed without merging**
